### ISSUE TITLE
can't get original language of reviews.

### ISSUE THREAD

**Issue by thachvv** [gaspa93/googlemaps-scraper#1]
Hi, 
I get reviews on the CSV file but can't get the original text (not in English).
How can I fix it?
Eg: 
(Translated by Google) When you come to Vietnam, visiting a beauty salon is a mandatory course  (Original) ë² íŠ¸ë‚¨ì— ì˜¤ë©´ ë¯¸ìž¥ì› ë°©ë¬¸ì´ í•„ìˆ˜ ì½”ìŠ¤ ì •ë‹µì´ë„¤ìš”

**Comment by gaspa93** [comment]
Hi @thachvv,

I did not find any option on Google Maps interface to enable/disable this feature: sometimes GM translates it, sometimes not. A possibility is to add a regular expression to filter the translated part, if present, but I would do it in a subsequent step, not directly when we scrape the data.
