### ISSUE TITLE
Limit to 900 reviews

### ISSUE THREAD

**Issue by Gwojda** [gaspa93/googlemaps-scraper#11]
Hi,
If i want to get all reviews from a big places (lets say a mcdo), i only get 900 reviews then google ban us : `urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fef9782ea20>: Failed to establish a new connection: [Errno 61] Connection refused` but i have to Ctrl+C your script to get this error 
(i think you are trying again, and again, and again... but google still ban you) ahah

**Comment by gaspa93** [comment]
Hi @Gwojda ,

this issue is the same pointed out in #8 
I am going to define a workaround.
