### ISSUE TITLE
scrape most relevant reviews

### ISSUE THREAD

**Issue by quaesito** [gaspa93/googlemaps-scraper#13]
Hi Mattia, 

Thansk for sharing your script, it works flawlessly!

I am now trying to re-adapt it to scrape 'most relevant reviews' rather than 'newest' ones.
However, if I change line 66 in googlemaps.py to pick the 'first element' rather than the 'second element', the __scroll function will not go through. 

I was wondering whether you faced this difficulty before.

Thanks in advance.

Cheers,
Michele

**Comment by gaspa93** [comment]
Hi @quaesito ,

thank you!
Sorry for the late response, but I have checked your PR and I see that you figured it out pretty well. 
Thank you very much for your support, and if you have other ideas for improvements we can get in touch.

**Comment by quaesito** [comment]
Hi @gaspa93,

No worries. The code works fine now for all --sort_by options except 'most_relevant'.
In such case, the __sort function is failing.

**Comment by gaspa93** [comment]
Hi,

ok, I will check why the function fails in that specific case only. I reopen the issue and I will work as soon as possible.

**Comment by quaesito** [comment]
Thanks @gaspa93
