### ISSUE TITLE
no use for MAX_SCROLL

### ISSUE THREAD

**Issue by thundermms** [gaspa93/googlemaps-scraper#20]
In your current code, there is no use for MAX_SCROLL, and I'm not sure why but all i get is this 
![review](https://user-images.githubusercontent.com/46366942/123602336-38055900-d82b-11eb-83b1-14c7897aa9ce.png)
please guide me on what needs to be done. 
this is the error message i get once i CTRL+C 
![error](https://user-images.githubusercontent.com/46366942/123602979-f3c68880-d82b-11eb-902f-544315c02f93.png)

**Comment by TheCaneda** [comment]
Hi,

I'm having the same trouble. Did you manage to solve it?

**Comment by matriim** [comment]
Has anyone solved it? I cant figure out how to make it do anything other than just scroll :(

**Comment by gaspa93** [comment]
Hi,

MAX_SCROLLS is a parameter that I set up before defining the file scraper.py, in which I use the input argument N to define end of scrolling: you can ignore it.
As for the tool, I updated master code with pull requests and a couple of commits, now it should work properly.

Let me know,
Mattia
