### ISSUE TITLE
Any chance of an update?

### ISSUE THREAD

**Issue by matriim** [gaspa93/googlemaps-scraper#21]
Hello guys and especially Gaspa!

This is just an amazing tool. Im an amateur in programming but I can see how advanced this tool is and manages to do quite a bit. If only there was an update to make it work. I've struggled with it for a few days but unfortunately Im just not at a level where I can fix it. 
It would be amazing if someone could update it.
Thank you again!

**Comment by gaspa93** [comment]
Hi @matriim,

I am very honoured to read this. 
Unfortunately I have been extremely busy at work during this period and I did not have any spare time to maintain the code. As soon as this moment passes, I will be back on this project and I will fix everything.

Thank you all for your patience,

Mattia

**Comment by gaspa93** [comment]
Hi, now it is working again.
Let me know if everything works fine by your side.

Mattia
