### ISSUE TITLE
Fails to click the sorting button

### ISSUE THREAD

**Issue by mattiacampana** [gaspa93/googlemaps-scraper#27]
Test to reproduce the problem:

1) urls.txt
> https://www.google.com/maps/place/Roadhouse+Restaurant+Pisa/@43.696512,10.3887242,17z/data=!4m7!3m6!1s0x12d591b4d21ce279:0x55bfd66c266e3a6e!8m2!3d43.6983437!4d10.3883958!9m1!1b1

2) `python scraper.py --N 50 --i urls.txt --debug`

3) `cat gm-scraper.log`
> 2022-04-14 16:22:02,936 - WARNING - Failed to click sorting button

**Comment by gaspa93** [comment]
Branch and latest commits should have solved all issues: a click is needed in order to accept/reject cookies
