### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException: Message: no such element: 

### ISSUE THREAD

**Issue by 7990satyam200** [gaspa93/googlemaps-scraper#30]
[Review 0]
Traceback (most recent call last):
  File "/Users/satyammishra/Desktop/sentiment_analysis/googlemaps-scraper/scraper.py", line 63, in <module>
    reviews = scraper.get_reviews(n)
  File "/Users/satyammishra/Desktop/sentiment_analysis/googlemaps-scraper/googlemaps.py", line 168, in get_reviews
    self.__scroll()
  File "/Users/satyammishra/Desktop/sentiment_analysis/googlemaps-scraper/googlemaps.py", line 278, in __scroll
    scrollable_div = self.driver.find_element(By.CSS_SELECTOR, 'div.siAUzd-neVct.section-scrollbox.cYB2Ge-oHo7ed.cYB2Ge-ti6hGc')
  File "/Users/satyammishra/opt/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 857, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/satyammishra/opt/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/Users/satyammishra/opt/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.siAUzd-neVct.section-scrollbox.cYB2Ge-oHo7ed.cYB2Ge-ti6hGc"}
  (Session info: headless chrome=103.0.5060.134)
Stacktrace:
0   chromedriver                        0x0000000102472ef9 chromedriver + 4480761
1   chromedriver                        0x00000001023fe5d3 chromedriver + 4003283
2   chromedriver                        0x0000000102091338 chromedriver + 410424
3   chromedriver                        0x00000001020c75bd chromedriver + 632253
4   chromedriver                        0x00000001020c7841 chromedriver + 632897
5   chromedriver                        0x00000001020f97d4 chromedriver + 837588
6   chromedriver                        0x00000001020e4a8d chromedriver + 752269
7   chromedriver                        0x00000001020f74f1 chromedriver + 828657
8   chromedriver                        0x00000001020e4953 chromedriver + 751955
9   chromedriver                        0x00000001020bacd5 chromedriver + 580821
10  chromedriver                        0x00000001020bbd25 chromedriver + 584997
11  chromedriver                        0x000000010244402d chromedriver + 4288557
12  chromedriver                        0x00000001024491b3 chromedriver + 4309427
13  chromedriver                        0x000000010244e23f chromedriver + 4330047
14  chromedriver                        0x0000000102449dfa chromedriver + 4312570
15  chromedriver                        0x0000000102422fef chromedriver + 4153327
16  chromedriver                        0x0000000102463d78 chromedriver + 4418936
17  chromedriver                        0x0000000102463eff chromedriver + 4419327
18  chromedriver                        0x000000010247aab5 chromedriver + 4512437
19  libsystem_pthread.dylib             0x00007ff811a524f4 _pthread_start + 1

**Comment by astrawnuts** [comment]
experiencing this issue too

**Comment by astrawnuts** [comment]
this person has fixed the issue for anyone who needs it
https://github.com/ryuuzake/googlemaps-scraper well done community and thank you original dev for developing this.

**Comment by gaspa93** [comment]
Branch highlighted by @astrawnuts and latest commits should have solved all issues: a click is needed in order to accept/reject cookies.
Bye,
Mattia

**Comment by astrawnuts** [comment]
If there is some way we could all help you with the development of this would be happy to make an anonymous donation of a small amount at @gaspa93. Is there any way we could do this?

**Comment by gaspa93** [comment]
Hi @astrawnuts thank you very much, it is wonderful that this work is so much appreciated and I will try to maintain and improve it as much as possible.
If you want to provide any kind of donation, you can send me through Paypal: paypal.me/mattiagaspa

Mattia

**Comment by astrawnuts** [comment]
Thank you Mattia :)
