### ISSUE TITLE
`__expand_reviews` sometimes not working

### ISSUE THREAD

**Issue by saito828koki** [gaspa93/googlemaps-scraper#37]
The position of `self.__scroll()` in these lines is incorrect, causing `self.__expand_reviews()` to be executed before the 'expand more' buttons are loaded. I believe that self.__scroll() was intended to be placed immediately after the comment `# scroll to load reviews`.
https://github.com/gaspa93/googlemaps-scraper/blob/b1bc007ecb3f212697536a31cbfb87dc9e4c0657/googlemaps.py#L163-L172

**Comment by gaspa93** [comment]
Thank you for notice this, MR approved
