### ISSUE TITLE
Fails to click sorting button

### ISSUE THREAD

**Issue by dimfu** [gaspa93/googlemaps-scraper#45]
Hi @gaspa93, I was attempting to scrape the following URL using the command python scraper.py --N 50 --i urls.txt --debug:
https://www.google.com/maps/place/The+Kutaya/@-8.7131747,115.18668,13z/data=!4m11!3m10!1s0x2dd2441f302d3927:0x7fdd6aa714bc38e1!5m2!4m1!1i2!8m2!3d-8.7389695!4d115.1673844!9m1!1b1!16s%2Fg%2F11cn5x9s4l?entry=ttu

However, the log displays a warning message stating, "Failed to click sorting button" after the script finishes running. Is there any way to fix this issue? Thank you!

**Comment by gaspa93** [comment]
Hi @dimfu ,

I checked and there was a problem in cooking acceptance click, with latest commit it should be fixed.
Bye,
Mattia

**Comment by JulesBelveze** [comment]
Hey @gaspa93 I am actually running into the same issue with the following url: https://www.google.com/maps/place/Siamsa/@48.8674543,2.3702251,17z/data=!3m1!4b1!4m6!3m5!1s0x47e66de2e49fdcd5:0xa5f43cd1c5dba4c0!8m2!3d48.8674543!4d2.3702251!16s%2Fg%2F1tm0b3hb?entry=ttu

Do you have any clue?
