### ISSUE TITLE
Recent comment

### ISSUE THREAD

**Issue by jasonkush** [gaspa93/googlemaps-scraper#5]
# Recent reviews won't work

Google changed the **role names**, so the most recent function no longer works.
I tried to change the role names, but it seems like that's not the only thing they have changed
![image](https://user-images.githubusercontent.com/43177690/82060964-a906b180-96fa-11ea-89b7-be2ec16913b3.png)

**Comment by gaspa93** [comment]
Hi,

thank you for the highlight: they changed both the role name and also the tag type, from <div> to <li>. Latest commit should fix the problem.

Cheers,

Mattia
