### ISSUE TITLE
On running this program i am getting a blank csv file

### ISSUE THREAD

**Issue by smidhunraj** [gaspa93/googlemaps-scraper#6]
I found this very useful . Can you please tell how to grab avatar link also

**Comment by gaspa93** [comment]
Hi,

is the title related with the question?
Anyway, the avatar picture link is available exactly as you see it in the page, with a 72x72 format. It is not a good quality, why do you need it? Graph representation maybe? Just curious,..
Anyway, the structure could be extracted with a formula like: 

`review.find('a', class='section-review-link')['style']`

but then a regular expression is needed to extract the correct url. I could add it as additional feature, would you like to help?

**Comment by alexgil55ka** [comment]
Hi,
I ran the example you posted and I’m also getting a blank CSV.

**Comment by gaspa93** [comment]
Hi,

yes it might happen. Did you use the latest version of the code?

**Comment by zaGuru** [comment]
> Hi,
> I ran the example you posted and I’m also getting a blank CSV.
> I also get a lot of ‘WARNING: Failed to click recent button’.
> Has this happened to you?

Hi Guys, did you manage to figure out how to fix this.

**Comment by alexgil55ka** [comment]
Hi, yeah I was able to get around it by using the debug argument. It wasn’t working for me because I think there’s an option where Google wants to know your location and you have to click now. I’ll probably start looking into trying to fix that. Let me know if that helps

**Comment by gaspa93** [comment]
Hi @alexgil55ka,

that popup should not appear I think, because of the option `options.add_argument("--disable-notifications")`. 

Anyway, the fact that debug mode runs reminds me a possible problem: it may happen that Google Maps tags change when chromedriver has the graphical components (`--debug` option) from when it has no graphic (normal mode).
It already happened once and I never figured out why, and for that reason there are different code for debug and not debug. Try to have a look at the specific HTML is passed to BeautifulSoap in normal mode, I think I will do it in next days.

**Comment by zaGuru** [comment]
Hi Guys, I found that i was not going to the actual reviews section on google maps and then using that link. It is working now. me bad!

**Comment by zaGuru** [comment]
Guys has anyone setup this scraper to use to scrape places from google maps. ie. if i go to google maps in chrome and search for food in an area. can the scraper grab all the places and list them in a csv file.

**Comment by gaspa93** [comment]
Hi @zaGuru ,
this feature is not present in the scraper right now, I tried to implement it some time ago but it was quite tricky to deal with the google maps search bar. We could work on it for sure, very interesting.

**Comment by nabilahsiti** [comment]
hi, i even tried with your link of examples, but I'm getting an empty dataset, with traceback error at the debug. can anybody help me with this?

**Comment by nabilahsiti** [comment]
> hi, i even tried with your link of examples, but I'm getting an empty dataset, with traceback error at the debug. can anybody help me with this?

im now getting this error. what do i do to fix this? "Google Maps JavaScript API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version", source: https://maps.googleapis.com/maps-api-v3/api/js/41/8/intl/en_gb/util.js (228)

**Comment by gaspa93** [comment]
Hi @nabilahsiti ,

this is weird, I have just run the current version of the script and it goes correctly: one thing that I needed to do was to update chromedriver to the latest version. You can download it here: https://chromedriver.storage.googleapis.com/index.html?path=86.0.4240.22/

Let me know if this fix the problem.
Cheers,

Mattia

**Comment by gaspa93** [comment]
Thank to the merged branch, now this feature is in place.
Bye,
Mattia
