### ISSUE TITLE
Failed to click recent button while debug works just fine

### ISSUE THREAD

**Issue by Lainnn** [gaspa93/googlemaps-scraper#7]
Hi, I ran this script on my previous computer and it works fine, but when I switched to my new computer, it keeps gives me "failed to click recent button", I checked debug and debug works just as it should, could you give me some idea how to solve this?

**Comment by Lainnn** [comment]
I tried the fork by venomouscyanide but it gives me error "2020-07-22 00:00:08,495 - INFO - Closing chromedriver..."
Then I tried the removed proxy branch, it gives me the error `Traceback (most recent call last):
  File "scraper.py", line 26, in <module>
    scraper.get_reviews(url, index)
  File "/home/lian/projects/research/new stuff/remove proxy/googlemaps-scraper-remove_proxy/googlemaps.py", line 85, in get_reviews
    recent_rating_bt = self.driver.find_elements_by_xpath('//div[@role=\'menuitem\']')[1]
IndexError: list index out of range
`

**Comment by venomouscyanide** [comment]
@Lainnn Which branch did you try to run in my fork?

**Comment by Lainnn** [comment]
> @Lainnn Which branch did you try to run in my fork?

Both master and remove proxy

**Comment by venomouscyanide** [comment]
@Lainnn I have updated 'remove_proxy` branch with the correct CSS selector for sorting by newest. Can you pull and try again?

**Comment by Lainnn** [comment]
> @Lainnn I have updated 'remove_proxy` branch with the correct CSS selector for sorting by newest. Can you pull and try again?

Sure! Thank you SO MUCH for the quick reply btw

**Comment by Lainnn** [comment]
> @Lainnn I have updated `remove_proxy` branch with the correct CSS selector for sorting by newest. Can you pull and try again?

It gave me this:`Traceback (most recent call last):
  File "scraper.py", line 26, in <module>
    scraper.get_reviews(url, index)
  File "/home/lian/projects/research/new stuff/remove proxy/googlemaps-scraper/googlemaps.py", line 66, in get_reviews
    menu_bt = wait.until(EC.element_to_be_clickable((By.XPATH, '//button[@data-value=\'Sort\']')))
  File "/home/lian/miniconda3/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
`
It does pull up a debug view, shows me that this website can't be reached.
I have no problem reaching the same url in my chrome so I would assume it's not my web connection problem

**Comment by venomouscyanide** [comment]
@Lainnn This usually happens because you are on the master branch and have not input the proxy creds in `proxy_setup.py`. If this occurred for you on remove_proxy branch then something is wrong.

**Comment by Lainnn** [comment]
@venomouscyanide Idk bud. I'm 100% sure I cloned the right one, I also tried the new branch you posted (fix_driver), also gives me the proxy error. idk about what I can do at this point

**Comment by venomouscyanide** [comment]
@Lainnn None of the branches including master will work without proxy. Only `remove_proxy` will work right out of the box. But if `remove_proxy` doesn't work for you, you might have better luck when @gaspa93 responds.

**Comment by Lainnn** [comment]
@venomouscyanide That's a lil sad, but thanks bud I really appreciate all your help tonight :))

**Comment by gaspa93** [comment]
Hi @Lainnn,

It is a recurrent issue, and I have not been able to eliminate it yet unfortunately. I think that the problem is related to google chrome, that uses OS options instead of the ones the scraper passes to the driver when you run it without graphical component.
 In fact, failure is due to the fact that the specific div to obtain the most recent reviews changes with respect to the language (I think): I will push a modification to have this part printed as a further debug.
By the way, are you using .com links? Language settings were the same across the two computers?

Thank you,

Mattia

**Comment by gaspa93** [comment]
Hi,

with the latest push on master I tried again to switch off this bug: now the language is set using `options.add_argument("--lang=en-GB")` and then the recent button is clicked in the same way both for debug and not debug.

I tested the code on OSX in English and on Windows 7 in Italian.
Let me know if it works for you, too.

Mattia
