### ISSUE TITLE
__parse_place function error

### ISSUE THREAD

**Issue by calvinnnlee** [gaspa93/googlemaps-scraper#9]
When running the scraper.py file, print(scraper.get_account(url)) in line 41 and 42 is never executed. I commented out the if statement and found an error under the __parse_place function in line 164 and 165. 

Error:

File "googlemaps.py", line 165, in __parse_place 

place['overall_rating'] = float(response.find('div', class_='gm2-display-2').text.replace(',', '.')) AttributeError: 'NoneType' object has no attribute 'text'

Tried using the required beautifulsoup, selenium version and tried different versions of chromedriver. That did not solve the issue. What could be the problem?

**Comment by gaspa93** [comment]
Hi,

latest commit to master fixed this issue: now I added a try-catch block for each field.
Bye,

Mattia
